"""Adding Google URL field to Google Books

Revision ID: 14bbb6c1efde
Revises: 98b551a34933
Create Date: 2024-09-11 16:44:49.406794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14bbb6c1efde'
down_revision = '98b551a34933'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_books_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('google_books_url')

    # ### end Alembic commands ###
