"""Changed password_hash to Text type

Revision ID: 83703f44e76a
Revises: f88c61c3c000
Create Date: 2024-09-09 13:13:21.445321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83703f44e76a'
down_revision = 'f88c61c3c000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###
